# Generated by Django 2.2.2 on 2019-06-27 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('name', models.CharField(max_length=150, primary_key=True, serialize=False, unique=True)),
                ('logo', models.FileField(upload_to='logos/')),
            ],
        ),
        migrations.CreateModel(
            name='Ammenity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ammenity_type', models.CharField(choices=[('HOSP', 'HOSPITAL'), ('SCH', 'SCHOOL'), ('POLICE STN', 'POLICE STATION'), ('MKT', 'MARKET')], default=None, max_length=10)),
                ('name', models.CharField(max_length=150)),
                ('distance', models.DecimalField(decimal_places=2, max_digits=11)),
            ],
            options={
                'verbose_name_plural': 'Ammenities',
            },
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_no', models.CharField(max_length=150, unique=True)),
                ('bedrooms', models.PositiveIntegerField()),
                ('sitting_rooms', models.PositiveIntegerField()),
                ('showers', models.PositiveIntegerField()),
                ('fitted_with_cctv', models.BooleanField(default=None)),
                ('verified', models.BooleanField(default=False)),
                ('for_sale', models.BooleanField(default=False)),
                ('for_rent', models.BooleanField(default=False)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='realestate.Agent')),
            ],
        ),
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot_no', models.CharField(max_length=150, unique=True)),
                ('size', models.DecimalField(decimal_places=2, help_text='Please enter the size in hectares.', max_digits=11)),
                ('verified', models.BooleanField(default=False)),
                ('for_sale', models.BooleanField()),
                ('for_rent', models.BooleanField()),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='realestate.Agent')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lodge', models.CharField(max_length=150, null=True)),
                ('room_no', models.CharField(max_length=150, unique=True)),
                ('shower', models.BooleanField(default=None)),
                ('town', models.CharField(max_length=20)),
                ('suburb', models.CharField(max_length=20)),
                ('room_type', models.CharField(choices=[('Single', 'single bed'), ('Double', 'Double bed')], max_length=10)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='realestate.Agent')),
            ],
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.FileField(unique=True, upload_to='images/')),
                ('Room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='realestate.Room')),
            ],
        ),
        migrations.CreateModel(
            name='LandImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.FileField(unique=True, upload_to='images/')),
                ('land', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='realestate.Land')),
            ],
        ),
        migrations.CreateModel(
            name='HouseImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.FileField(unique=True, upload_to='images/')),
                ('house', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='realestate.House')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel', models.CharField(help_text='Please use the following format +254 70000000', max_length=15)),
                ('email_address', models.EmailField(max_length=254)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommercialLand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, help_text='price in KSH', max_digits=11)),
                ('status', models.BooleanField(default=True, help_text='if checked the property is available')),
                ('plot_no', models.CharField(max_length=150, unique=True)),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realestate.Land')),
            ],
            options={
                'verbose_name_plural': 'Commerial_lands',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='CommercialHouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, help_text='price in KSH', max_digits=11)),
                ('status', models.BooleanField(default=True, help_text='if checked the property is available')),
                ('house_no', models.CharField(max_length=150, unique=True)),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realestate.House')),
            ],
            options={
                'verbose_name_plural': 'Commerial_houses',
                'ordering': ['price'],
            },
        ),
    ]
