# Generated by Django 2.2.1 on 2019-06-30 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0002_auto_20190629_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='price',
            field=models.DecimalField(decimal_places=2, default=None, help_text='price in KSH', max_digits=11),
        ),
        migrations.AddField(
            model_name='land',
            name='price',
            field=models.DecimalField(decimal_places=2, default=None, help_text='price in KSH', max_digits=11),
        ),
        migrations.AddField(
            model_name='room',
            name='price',
            field=models.DecimalField(decimal_places=2, default=None, help_text='price in KSH', max_digits=11),
        ),
    ]
