# Generated by Django 2.2.1 on 2019-07-01 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0003_auto_20190630_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='commercial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='land',
            name='commercial',
            field=models.BooleanField(default=False),
        ),
    ]
