# Generated by Django 2.2.1 on 2019-07-04 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0005_auto_20190704_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='suburb',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='land',
            name='town',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
