# Generated by Django 2.1.5 on 2019-07-19 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0009_auto_20190715_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bedrooms', models.PositiveIntegerField()),
                ('sitting_rooms', models.PositiveIntegerField()),
                ('showers', models.PositiveIntegerField()),
                ('town', models.CharField(max_length=100)),
                ('suburb', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=None, help_text='price in KSH', max_digits=11)),
            ],
        ),
        migrations.CreateModel(
            name='LandRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.DecimalField(decimal_places=2, help_text='Please enter the size in hectares.', max_digits=11)),
                ('town', models.CharField(max_length=100)),
                ('suburb', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=None, help_text='price in KSH', max_digits=11)),
            ],
        ),
        migrations.CreateModel(
            name='RoomRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('town', models.CharField(max_length=20)),
                ('suburb', models.CharField(max_length=20)),
                ('room_type', models.CharField(choices=[('Single', 'single bed'), ('Double', 'Double bed')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, default=None, help_text='price in KSH', max_digits=11)),
            ],
        ),
    ]
