from django.contrib import admin
from .models import *

admin.site.register(Agent)
admin.site.register(Ammenity)
admin.site.register(House)
admin.site.register(Room)
admin.site.register(Land)
# admin.site.register(AquisationType)
# admin.site.register(HouseForRent)
# admin.site.register(HouseForSale)
# admin.site.register(LandForSale)
# admin.site.register(LandForRent)
admin.site.register(CommercialLand)
admin.site.register(CommercialHouse)
admin.site.register(CustomerContact)
admin.site.register(HouseImage)
admin.site.register(RoomImage)
admin.site.register(LandImage)
admin.site.register(RoomRequest)
admin.site.register(LandRequest)
admin.site.register(HouseRequest)
